# Lab Test 05

## Kindly follow the given instructions below
1. Download this file.
2. Rename your file with your ID like.,
    - *YourName - LT05 - YOUR_ROLL_NUMBER*  ==>  $\color{blue}{\text{Muhammad Nadeem - LT05 - 201980050}}$
3. Write solution of every question in its respective cell or block.
4. Upload this file with your solutions.
5. There will be **NO** any other file to be submitted.
6. Penalty for plagirisam is to be straight **ZERO**.
7. NO LATE SUBMISSION.
8. $\color{red}{\text{LATE SUBMISSION WILL BE MARKED ZERO}}$

### See the question on the white board

In [15]:
# Write your code here.
import numpy as np
a=np.array([[7,8,9,5,6,3,1],[2,1,8,6,2,5,6],[8,9,6,1,5,7,6],[7,5,8,9,8,3,1]])
print(a)
# Finally get
#  [8 5 6]
#  [8 3 1]
# by slicing

[[7 8 9 5 6 3 1]
 [2 1 8 6 2 5 6]
 [8 9 6 1 5 7 6]
 [7 5 8 9 8 3 1]]


In [30]:
a1=a[:1,1:3]
print(a1)
l2=a[1:2]
print(l2)
l4=a[3:4]
print(l4)
print()
print(a[1:3, 2:5])
print()

print(l2,l4)






[[8 9]]
[[2 1 8 6 2 5 6]]
[[7 5 8 9 8 3 1]]

[[8 6 2]
 [6 1 5]]

[[2 1 8 6 2 5 6]] [[7 5 8 9 8 3 1]]


In [31]:
# Write your code here.
import numpy as np
a=np.array([[7,8,9,5,6,3,1],[2,1,8,6,2,5,6],[8,9,6,1,5,7,6],[7,5,8,9,8,3,1]])
print(a)
# Finally get
#  [8 5 6]
#  [8 3 1]
# by slicing

a.shape

[[7 8 9 5 6 3 1]
 [2 1 8 6 2 5 6]
 [8 9 6 1 5 7 6]
 [7 5 8 9 8 3 1]]


(4, 7)

In [36]:
# Write your code here.
import numpy as np
a=np.array([[7,8,9,5,6,3,1],[2,1,8,6,2,5,6],[8,9,6,1,5,7,6],[7,5,8,9,8,3,1]])
print(a)
# Finally get
#  [8 5 6]
#  [8 3 1]
# by slicing
print()
b=a.reshape(2,14)
print(b)

[[7 8 9 5 6 3 1]
 [2 1 8 6 2 5 6]
 [8 9 6 1 5 7 6]
 [7 5 8 9 8 3 1]]

[[7 8 9 5 6 3 1 2 1 8 6 2 5 6]
 [8 9 6 1 5 7 6 7 5 8 9 8 3 1]]


In [46]:
print(b[:1,])
q=b[:1,1:3:2]
r=b[:1,1:6:2]
print(r)

[[7 8 9 5 6 3 1 2 1 8 6 2 5 6]]
[[8 5 3]]


In [43]:
print(b[1:2])

[[8 9 6 1 5 7 6 7 5 8 9 8 3 1]]
