# Class Partipation 06

## Kindly follow the given instructions below
1. Download this file.
2. Rename your file with your ID like.,
    - *YOUR_NAME - CP07 - YOUR_ROLL_NUMBERR* ==> $\color{blue}{\text{Muhammad Nadeem - CP06 - 201980050}}$
3. Write your solution of every question in its respective cell or block.
4. Upload this file with your solutions.
5. There will be **NO** any other file to be submitted.
6. Penalty for plagirisam is to be straight **ZERO**.
7. **NO LATE SUBMISSION.**
8. $\color{red}{\text{LATE SUBMISSION WILL BE MARKED ZERO}}$

### Exercise-01

Create an array of table 02 unig Numpy Array and then Iterate it.

In [2]:
# write your code here.
import numpy as np

my_array = np.array([[12, 23], [43, 54]])
for row in my_array:
    for element in row:
        print(element)


12
23
43
54


### Exercise-02

Create 8-by-8 matrix and fill it with a pattern of checkerboard like
    
    # 0 1 0
    # 1 0 1
    # 0 1 0

In [3]:
# write your code here.
import numpy as np

# Create an 8-by-8 matrix of zeros
matrix = np.zeros((8, 8), dtype=int)

# Set every other element in each row and column to 1
for i in range(8):
    for j in range(8):
        if (i+j)%2 == 0:
            matrix[i, j] = 1

# Print the resulting matrix
print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### Exercise-03

Create 10-by-10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [4]:
# write your code here.
import numpy as np

# Create a 10-by-10 matrix of zeros
matrix = np.zeros((10, 10), dtype=int)

# Set the border elements to 1
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

# Print the resulting matrix
print(matrix)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### Exercise-04

Create a given matrix first then find the number of rows and columns.
    
    # [[10 11 12 13]
    # [14 15 16 17]
    # [18 19 20 21]]

In [5]:
# write your code here.
import numpy as np

# Create a 3-by-4 matrix with the given values
matrix = np.array([[10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]])

# Print the resulting matrix
print(matrix)
# Find the number of rows and columns
num_rows, num_cols = matrix.shape

# Print the number of rows and columns
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")



[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows: 3
Number of columns: 4


### Exercise-05

Reshape above 2-D array to one dimensional array

In [6]:
# write your code here.
import numpy as np

# Create a 3-by-4 matrix with the given values
matrix = np.array([[10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]])

# Reshape the matrix to a one-dimensional array
one_dim_array = matrix.reshape(-1)

# Print the resulting one-dimensional array
print(one_dim_array)


[10 11 12 13 14 15 16 17 18 19 20 21]


### Exercise-06

Create a 5-by-7 matrix filled with values from 55 to 90

In [7]:
# write your code here.
import numpy as np

# Create a 5-by-7 matrix with values from 55 to 90
matrix = np.arange(55, 55+35).reshape((5,7))

# Print the resulting matrix
print(matrix)


[[55 56 57 58 59 60 61]
 [62 63 64 65 66 67 68]
 [69 70 71 72 73 74 75]
 [76 77 78 79 80 81 82]
 [83 84 85 86 87 88 89]]
